# Site settings
title: CommunityData Styleguide
email: info@folklabs.com
description: "Community Data is a web project to offer citizens better ways to create open data visualizations."
baseurl: /communitydata-styleguide
url: "http://folklabs.com"

# Build settings
markdown: kramdown
permalink: pretty
# gems: ['jekyll-haml']

collections:
- blocks
